s0558738/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :customers do
    resources :articles
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

s0558738/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

s0558738/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :customer
end

s0558738/app/models/customer.rb
class Customer < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :name, presence: true,
            length: { minimum: 3 }
end

s0558738/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

s0558738/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def create
    @customer = Customer.find(params[:customer_id])
    @article = @customer.articles.create(article_params)
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @article = @customer.articles.find(params[:id])
    @article.destroy
    redirect_to customer_path(@customer)
  end

  private
  def article_params
    params.require(:article).permit(:name, :body)
  end
end

s0558738/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :text)
  end
end

s0558738/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

s0558738/app/helpers/application_helper.rb
module ApplicationHelper
end

s0558738/app/helpers/articles_helper.rb
module ArticlesHelper
end

s0558738/app/helpers/customers_helper.rb
module CustomersHelper
end

s0558738/app/helpers/welcome_helper.rb
module WelcomeHelper
end

s0558738/app/views/articles/_article.html.erb
<p>
  <strong>name:</strong>
  <%= article.name %>
</p>

<p>
  <strong>article:</strong>
  <%= article.body %>
</p>

<p>
  <%= link_to 'Destroy Article', [article.customer, article],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

s0558738/app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>

  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this customer from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

s0558738/app/views/customers/edit.html.erb
<h1>Edit customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

s0558738/app/views/customers/index.html.erb
<h1>Listing Customers</h1>
<%= link_to 'New Customer', new_customer_path %>
<table>
  <tr>
    <th>name</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.text %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      <td><%= link_to 'Destroy', customer_path(customer),
                      method: :delete,
                      data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

s0558738/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

s0558738/app/views/customers/show.html.erb
<p>
  <strong>name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @customer.text %>
</p>

<h2>articles</h2>
<%= render @customer.articles %>

<h2>Add a article:</h2>
<%= form_with(model: [ @customer, @customer.articles.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

s0558738/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S0558738</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

s0558738/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My customers', controller: 'customers' %>